name: biomaster-md-openmm
channels:
  - conda-forge
dependencies:
  - python=3.11
  - cuda-version=12.9
  - openmm=8.5
  - ambertools=24
  - pdbfixer=1.12
  - parmed=4.3
  - openmmforcefields=0.16
  - openff-toolkit=0.18
  - mdtraj=1.11
  - mdanalysis=2.10
