import { useEffect, useMemo, useRef, useState } from 'react';
import './affinity-atlas.css';
type Axis={id:string;name:string};
type Data={drugs:Axis[];targets:Axis[];cells:number[][];counts:Record<string,number>;sources:string[];endpoint:string;threshold_nM:number;outside_planned_pairs:number;uploaded_rows:number;inventory:{total_rows:number;auxiliary_rows:number;exact_rows:number;exact_pairs:number;kd_ki_pairs:number;kd_equal_pairs:number;source_rows:Record<string,number>;legacy:{name:string;count:number;note:string;path:string}[];quality_reviews:unknown[];notes:string[]}};
const BLOCK=24;
const densityBase=[232,237,244];
const DENSITY_CAP=0.10;
const densityLevels=[0,0.002,0.005,0.01,0.02,0.05,DENSITY_CAP];
const densityColors:Record<string,string>={measured:'#047857',planned:'#b77900',uploaded:'#1d4ed8',lower:'#047857',higher:'#c24136',conflicting:'#7c3aad',uncertain:'#b77900'};
function densityColor(status:string,ratio:number){const hex=densityColors[status];const weight=Math.sqrt(Math.max(0,Math.min(1,ratio/DENSITY_CAP)));return `rgb(${densityBase.map((v,i)=>Math.round(v+(parseInt(hex.slice(1+i*2,3+i*2),16)-v)*weight)).join(',')})`;}

const colors:Record<string,string>={unknown:'#dde3ed',measured:'#14b89b',planned:'#f5b444',uploaded:'#4c85ff',lower:'#14b89b',higher:'#ed705d',conflicting:'#a783ed',uncertain:'#f5b444'};
const labels:Record<string,string>={unknown:'无所选证据',measured:'外部数值证据',planned:'设计待测',uploaded:'SPR 已提交（待审核）',lower:'满足所选阈值',higher:'高于所选阈值',conflicting:'阈值结论冲突',uncertain:'暂不可判定'};
const format=(n:number)=>n.toLocaleString('en-US');
function state(c:number[]|undefined,mode:string){if(!c)return 'unknown';if(mode==='coverage')return c[7]?'uploaded':c[2]?'measured':c[6]?'planned':'unknown';return c[3]&&c[4]?'conflicting':c[3]?'lower':c[4]?'higher':c[2]||c[7]?'uncertain':'unknown';}
export default function AffinityAtlas(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const [mode,setMode]=useState('coverage'),[endpoint,setEndpoint]=useState('Kd'),[threshold,setThreshold]=useState('1000'),[source,setSource]=useState('all'),[revision,setRevision]=useState(0);
 const [block,setBlock]=useState<[number,number]>([0,0]),[pair,setPair]=useState<[number,number]|null>(null),[pairData,setPairData]=useState<{items:Record<string,any>[];total:number;uploaded:Record<string,any>[]}|null>(null),[pairError,setPairError]=useState('');
 const [hoverBlock,setHoverBlock]=useState<[number,number]|null>(null);
 const [drugQuery,setDrugQuery]=useState(''),[targetQuery,setTargetQuery]=useState('');
 const canvas=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');fetch(`/api/affinity-matrix?endpoint=${endpoint}&threshold=${threshold}&source=${encodeURIComponent(source)}`,{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d;}).then(d=>setData(d)).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[endpoint,threshold,source,revision]);
 const cells=useMemo(()=>new Map((data?.cells||[]).map(c=>[`${c[0]}:${c[1]}`,c])),[data]);
 const blockRows=Math.ceil((data?.drugs.length||0)/BLOCK),blockCols=Math.ceil((data?.targets.length||0)/BLOCK);
 const blocks=useMemo(()=>{const out=new Map<string,Record<string,number>>();for(const c of data?.cells||[]){const k=`${Math.floor(c[0]/BLOCK)}:${Math.floor(c[1]/BLOCK)}`;if(!out.has(k))out.set(k,{});const s=state(c,mode);if(s!=='unknown'){const counts=out.get(k)!;counts[s]=(counts[s]||0)+1;};}return out;},[data,mode]);
 useEffect(()=>{const el=canvas.current;if(!el||!data)return;const ctx=el.getContext('2d');if(!ctx)return;const unit=18;el.width=blockCols*unit;el.height=blockRows*unit;ctx.fillStyle='#0d1c32';ctx.fillRect(0,0,el.width,el.height);for(let r=0;r<blockRows;r++)for(let t=0;t<blockCols;t++){const counts=blocks.get(`${r}:${t}`)||{};const parts=Object.keys(densityColors).filter(s=>counts[s]);const denominator=Math.min(BLOCK,data.drugs.length-r*BLOCK)*Math.min(BLOCK,data.targets.length-t*BLOCK);ctx.fillStyle='rgb(232,237,244)';ctx.fillRect(t*unit+2,r*unit+2,unit-4,unit-4);parts.forEach((s,i)=>{ctx.fillStyle=densityColor(s,counts[s]/denominator);ctx.fillRect(t*unit+2+i*(unit-4)/parts.length,r*unit+2,(unit-4)/parts.length,unit-4);});}ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.strokeRect(block[1]*unit+1,block[0]*unit+1,unit-2,unit-2);},[data,blockRows,blockCols,blocks,block]);
 useEffect(()=>{if(!pair||!data)return;const c=new AbortController();setPairData(null);setPairError('');fetch(`/api/affinity-pair?drug=${data.drugs[pair[0]].id}&target=${data.targets[pair[1]].id}`,{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d;}).then(setPairData).catch(e=>{if(e.name!=='AbortError')setPairError(e.message);});return()=>c.abort();},[pair,data]);
 if(error)return <section className="panel" role="alert">{error}<button onClick={()=>setRevision(r=>r+1)}>重试加载</button></section>;
 if(!data)return <section className="panel" role="status">正在汇总亲和证据与实验计划…</section>;
 const inv=data.inventory,legend=mode==='coverage'?['measured','planned','uploaded','unknown']:['lower','higher','conflicting','uncertain','unknown'];
 const globalCounts:Record<string,number>={unknown:data.drugs.length*data.targets.length};for(const c of data.cells){const s=state(c,mode);if(s!=='unknown'){globalCounts[s]=(globalCounts[s]||0)+1;globalCounts.unknown--;}}
 const localDrugs=data.drugs.slice(block[0]*BLOCK,(block[0]+1)*BLOCK),localTargets=data.targets.slice(block[1]*BLOCK,(block[1]+1)*BLOCK);
 const focusedBlock=hoverBlock||block;const focusedCounts=blocks.get(`${focusedBlock[0]}:${focusedBlock[1]}`)||{};const focusedTotal=Math.min(BLOCK,data.drugs.length-focusedBlock[0]*BLOCK)*Math.min(BLOCK,data.targets.length-focusedBlock[1]*BLOCK);
 const localCounts:Record<string,number>={};for(let d=0;d<localDrugs.length;d++)for(let t=0;t<localTargets.length;t++){const s=state(cells.get(`${block[0]*BLOCK+d}:${block[1]*BLOCK+t}`),mode);localCounts[s]=(localCounts[s]||0)+1;}
 return <div className="affinity-atlas">
 <header className="aa-hero"><span>EXPERIMENTAL EVIDENCE ATLAS</span><h1>亲和证据 · 点亮矩阵</h1><p>{data.drugs.length} 个药物 × {data.targets.length} 个靶点，{format(data.drugs.length*data.targets.length)} 个精确配对位置。全局看覆盖，局部看实验。</p></header>
 <div className="aa-stats">{[[format(inv.total_rows),'入库测量 / 拟合 / 响应行'],[format(inv.exact_pairs),'最新质控后精确覆盖配对'],[format(inv.kd_equal_pairs),'具有 Kd 等值记录的配对'],[format(data.uploaded_rows),'项目 SPR 提交记录']].map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</div>
 <section className="aa-card"><div className="aa-controls"><div className="aa-tabs" role="group" aria-label="矩阵视图"><button aria-pressed={mode==='coverage'} onClick={()=>setMode('coverage')}>实验覆盖 · 已测 / 待测</button><button aria-pressed={mode==='affinity'} onClick={()=>setMode('affinity')}>亲和结果 · 阈值分层</button></div><label>来源<select aria-label="矩阵证据来源" value={source} onChange={e=>setSource(e.target.value)}><option value="all">全部已映射来源</option>{data.sources.map(s=><option key={s}>{s}</option>)}</select></label>{mode==='affinity'&&<><label>端点<select aria-label="亲和端点" value={endpoint} onChange={e=>setEndpoint(e.target.value)}><option>Kd</option><option>Ki</option></select></label><label>分层阈值<select aria-label="亲和分层阈值" value={threshold} onChange={e=>setThreshold(e.target.value)}>{['100','1000','10000'].map(v=><option key={v} value={v}>{format(Number(v))} nM</option>)}</select></label></>}<button onClick={()=>setRevision(r=>r+1)}>刷新证据</button></div>
 <p className="aa-note">{mode==='coverage'?'绿色表示存在精确数值证据（可能是 Kd、Ki、IC50 或 EC50），不是全部为 SPR 或阳性。黄色只表示已进入基线设计且无提交记录；其余空白不自动称为待测。':'绿色表示所选 Kd 或 Ki 满足 ≤ 阈值；红色表示高于阈值，不等同绝对“不结合”。上下界不能确定时保留待判定，两侧记录同时存在时显示冲突。IC50 / EC50 和待审核 SPR 不自动转成结合结论。'}</p>
 <div className="aa-legend">{legend.map(s=><span key={s}><i style={{background:colors[s]}}/>{labels[s]} · {format(globalCounts[s]||0)}</span>)}</div>
 {loading&&<p role="status">正在更新筛选，以下矩阵暂为上次结果…</p>}
 <div className="aa-matrix-layout" style={loading?{opacity:.5,pointerEvents:'none'}:undefined}><div className="aa-overview"><div className="aa-section-title"><h2>全局缩略图</h2><span>{blockRows} × {blockCols} 个汇总块</span></div><p>每块最多 24 药 × 24 靶点。各色带按真实占比做平方根增强，≥10% 达到最深色（不代表全部完成）。少量记录也可见，悬停查看实际比例。点击放大。</p><div className="aa-density-scales">{legend.filter(s=>s!=='unknown').map(s=><div key={s}><span>{labels[s]}</span><div className="aa-density-swatches">{densityLevels.map(p=><span key={p}><i style={{background:densityColor(s,p)}}/><small>{p===DENSITY_CAP?'≥':''}{Number((p*100).toFixed(1))}%</small></span>)}</div></div>)}</div><canvas ref={canvas} onMouseLeave={()=>setHoverBlock(null)} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();const next:[number,number]=[Math.min(blockRows-1,Math.floor((e.clientY-r.top)/r.height*blockRows)),Math.min(blockCols-1,Math.floor((e.clientX-r.left)/r.width*blockCols))];setHoverBlock(old=>old?.[0]===next[0]&&old?.[1]===next[1]?old:next);}} aria-label="亲和证据全局概览，使用下方行列选择可键盘定位" onClick={e=>{const r=e.currentTarget.getBoundingClientRect();setBlock([Math.min(blockRows-1,Math.floor((e.clientY-r.top)/r.height*blockRows)),Math.min(blockCols-1,Math.floor((e.clientX-r.left)/r.width*blockCols))]);}}/><div className="aa-density-readout" aria-live="polite"><strong>{hoverBlock?'悬停块':'选中块'} · 共 {focusedTotal} 对</strong>{legend.filter(s=>s!=='unknown').map(s=><span key={s}>{labels[s]}：{focusedCounts[s]||0} / {focusedTotal}（{((focusedCounts[s]||0)/focusedTotal*100).toFixed(2)}%）</span>)}</div><div className="aa-block-controls"><label>药物块<select aria-label="选择药物块" value={block[0]} onChange={e=>setBlock([Number(e.target.value),block[1]])}>{Array.from({length:blockRows},(_,i)=><option key={i} value={i}>{i*BLOCK+1}–{Math.min((i+1)*BLOCK,data.drugs.length)}</option>)}</select></label><label>靶点块<select aria-label="选择靶点块" value={block[1]} onChange={e=>setBlock([block[0],Number(e.target.value)])}>{Array.from({length:blockCols},(_,i)=><option key={i} value={i}>{i*BLOCK+1}–{Math.min((i+1)*BLOCK,data.targets.length)}</option>)}</select></label></div></div>
 <div className="aa-local"><div className="aa-section-title"><h2>局部精确格点</h2><span>一格 = 一个配对</span></div><p>纵轴：{localDrugs[0]?.name} … {localDrugs.at(-1)?.name}<br/>横轴：{localTargets[0]?.name} … {localTargets.at(-1)?.name}</p><div className="aa-grid" style={{gridTemplateColumns:`repeat(${localTargets.length},1fr)`}}>{localDrugs.flatMap((d,i)=>localTargets.map((t,j)=>{const dr=block[0]*BLOCK+i,tr=block[1]*BLOCK+j,s=state(cells.get(`${dr}:${tr}`),mode);return <button key={`${dr}:${tr}`} aria-label={`${d.name} → ${t.name}：${labels[s]}`} title={`${d.name} → ${t.name}：${labels[s]}`} className={pair?.[0]===dr&&pair?.[1]===tr?'selected':''} style={{background:colors[s]}} onClick={()=>setPair([dr,tr])}/>;}))}</div><div className="aa-local-counts">{legend.map(s=><span key={s}>{labels[s]} <b>{localCounts[s]||0}</b></span>)}</div>
 <details><summary>通过名称定位具体配对</summary><label>药物<input aria-label="定位药物" value={drugQuery} onChange={e=>setDrugQuery(e.target.value)} placeholder="输入名称或完整 InChIKey"/></label><select aria-label="定位药物匹配项" value="" onChange={e=>{const d=Number(e.target.value),t=pair?.[1]??block[1]*BLOCK;setPair([d,t]);setBlock([Math.floor(d/BLOCK),Math.floor(t/BLOCK)]);}}><option value="">选择药物</option>{data.drugs.map((d,i)=>({...d,i})).filter(d=>`${d.name} ${d.id}`.toLowerCase().includes(drugQuery.toLowerCase())).slice(0,100).map(d=><option key={d.id} value={d.i}>{d.name}</option>)}</select><label>靶点<input aria-label="定位靶点" value={targetQuery} onChange={e=>setTargetQuery(e.target.value)} placeholder="输入基因或 ChEMBL ID"/></label><select aria-label="定位靶点匹配项" value="" onChange={e=>{const t=Number(e.target.value),d=pair?.[0]??block[0]*BLOCK;setPair([d,t]);setBlock([Math.floor(d/BLOCK),Math.floor(t/BLOCK)]);}}><option value="">选择靶点</option>{data.targets.map((t,i)=>({...t,i})).filter(t=>`${t.name} ${t.id}`.toLowerCase().includes(targetQuery.toLowerCase())).slice(0,100).map(t=><option key={t.id} value={t.i}>{t.name} · {t.id}</option>)}</select></details></div></div>
 <p className="aa-note">矩阵按名称排序、固定轴顺序；未进入 720 药登记的 {data.outside_planned_pairs} 个设计配对另行保留，不强行映射。扩展证据池不自动认定为已安排待测。历史 Davis / GtoPdb 等未统一身份复核的资源见下表，暂不强行点亮。</p></section>
 {pair&&<section className="aa-card" aria-label="矩阵配对证据"><h2>{data.drugs[pair[0]].name} → {data.targets[pair[1]].name}</h2><p>{data.drugs[pair[0]].id} · {data.targets[pair[1]].id}</p><a href={`#/drug/${data.drugs[pair[0]].id}/experiments`}>打开药物档案</a> · <a href={`#/target/${data.targets[pair[1]].id}/experiments`}>打开靶点档案</a><p>以下为该配对的全部端点和来源，包含被暂扣记录；矩阵颜色仅使用当前筛选且未被质控排除的证据。</p>{pairError?<p role="alert">{pairError}</p>:!pairData?<p role="status">正在读取原始数值证据…</p>:<><p>{pairData.total} 条来源数值记录 · {pairData.uploaded.length} 条 SPR 提交记录（待审核）</p><div className="aa-table"><table><thead><tr><th>来源 / 记录</th><th>端点</th><th>关系 / nM</th><th>方法与质控</th><th>文献</th></tr></thead><tbody>{pairData.items.map(r=><tr key={r.id}><td>{r.source}<small>{r.record_id}</small></td><td>{r.endpoint}</td><td>{r.relation} {r.value_nM}</td><td>{r.quality_review||r.quality}<small>{r.method||'方法待复核'} · 构建未经序列核验</small></td><td>{r.doi||r.pmid||'未附文献号'}{r.source_url&&/^https?:\/\//.test(r.source_url)&&<a href={r.source_url} target="_blank" rel="noreferrer">查看来源</a>}</td></tr>)}</tbody></table></div>{!pairData.total&&<p>当前精确证据库未收录此配对；不能据此认定不结合。</p>}{pairData.uploaded.map((r,i)=><p key={i}>SPR · {r.batch} / {r.sample_id} · {r.result} · KD {r.KD??'—'} {r.KD_unit} · 质控 {r.qc} · 待审核</p>)}</>}</section>}
 <section className="aa-card"><h2>完整资源规模 · 分层计数</h2><p>八个来源共 {format(inv.total_rows)} 条测量 / 拟合 / 响应行，另有 {format(inv.auxiliary_rows)} 条辅助观察。最新质控后 {format(inv.exact_rows)} 条合格数值记录落在 {format(inv.exact_pairs)} 个项目配对；其中 {format(inv.kd_ki_pairs)} 对有 Kd 或 Ki。</p><div className="aa-table"><table><thead><tr><th>当前证据库来源</th><th>入库行数</th><th>口径</th></tr></thead><tbody>{Object.entries(inv.source_rows).map(([s,n])=><tr key={s}><td>{s}</td><td>{format(n)}</td><td>{s.startsWith('BindingDB')?'完整归档的项目邻域索引；混合端点':s.startsWith('ChEMBL')?'既有项目数值记录；不是全库活性总量':s.startsWith('HiQ')?'结构附带既有标签；不是独立新实验':s.startsWith('RAF')?'kinobead 响应；非亲和常数':s.startsWith('Super')?'表观 Kd；不并入纯蛋白 Kd':'含拟合 / 响应 / 质控；限定实验构建'}</td></tr>)}</tbody></table></div><h3>历史资源与派生子集（不可与上表相加）</h3><div className="aa-table"><table><thead><tr><th>资源</th><th>规模</th><th>计数与边界</th></tr></thead><tbody>{inv.legacy.map(r=><tr key={r.name}><td>{r.name}</td><td>{format(r.count)}</td><td>{r.note}<small>{r.path}</small></td></tr>)}</tbody></table></div>{inv.notes.map(n=><p className="aa-note" key={n}>{n}</p>)}<p className="aa-note">已应用 {inv.quality_reviews.length} 条后续来源质控决定；旧审计 8,458 对保留为历史快照，当前显示 {format(inv.exact_pairs)} 对。矩阵是证据覆盖与阈值探索工具，不是模型命中率证明。</p></section>
 </div>;
}
